[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fee_distribution = "11111111111111111111111111111111"

[programs.mainnet]
fee_distribution = "11111111111111111111111111111111"

[programs.testnet]
fee_distribution = "6iCBP3de8RKFhUbXVRNvrbV6Ki83JHTmge6tNGvcGiEm"

[registry]
url = "https://api.github.com/repos/coral-xyz/anchor/releases/download"

[provider]
cluster = "testnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha --require ts-node/register tests/**/*.ts"
